"""Add constraints to ProjectDonationModel

Revision ID: 84153d692d88
Revises: f87365da8746
Create Date: 2024-06-27 23:22:32.798884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84153d692d88'
down_revision = 'f87365da8746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
