"""Add min_anystr_length to ProjectDonationModel

Revision ID: 865f11ffcb4a
Revises: 84153d692d88
Create Date: 2024-06-27 23:33:18.745844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865f11ffcb4a'
down_revision = '84153d692d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
