"""Remove default close_date

Revision ID: f87365da8746
Revises: fe7a85a1d812
Create Date: 2024-06-27 04:42:26.558148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87365da8746'
down_revision = 'fe7a85a1d812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
